[font]
size = 20.0

[font.normal]
family = "Hack Nerd Font Mono"

[window]
startup_mode = "Maximized"
dynamic_padding = false
opacity = 0.90
decorations = "full"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[cursor]
style = "Beam"

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
# background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
